### ISSUE TITLE
Fix path to migrations in readme

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac-db#67]
`implode(DIRECTORY_SEPARATOR, [dirname(__DIR__), 'vendor', 'yiisoft', 'rbac', 'migrations', 'assignments']),`

1) incorrect path after vendor
2) replace to more simple `dirname(__DIR__).'/vendor/yiisoft/...'`

**Comment by arogachev** [comment]
1. Where exactly the error is?
2. Isn't using `DIRECTORY_SEPARATOR` more versatile?

**Comment by samdark** [comment]
`implode()` usage is less readable.

**Comment by vjik** [comment]
> * Where exactly the error is?

![image](https://github.com/yiisoft/rbac-db/assets/525501/e7c941f9-8af7-46b2-bca8-2951a59c842f)

> * Isn't using `DIRECTORY_SEPARATOR` more versatile?

It's configuration for concrete case (often it will be Linux), versatile not need here.  Also `/` work both for linux and windows.
